// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: authentication/v1/groups.proto

package authenticationv1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/ZacharyLangley/igru-web-server/pkg/proto/authentication/v1"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// GroupServiceName is the fully-qualified name of the GroupService service.
	GroupServiceName = "authentication.v1.GroupService"
)

// GroupServiceClient is a client for the authentication.v1.GroupService service.
type GroupServiceClient interface {
	CreateGroup(context.Context, *connect_go.Request[v1.CreateGroupRequest]) (*connect_go.Response[v1.CreateGroupResponse], error)
	UpdateGroup(context.Context, *connect_go.Request[v1.UpdateGroupRequest]) (*connect_go.Response[v1.UpdateGroupResponse], error)
	DeleteGroup(context.Context, *connect_go.Request[v1.DeleteGroupRequest]) (*connect_go.Response[v1.DeleteGroupResponse], error)
	GetGroup(context.Context, *connect_go.Request[v1.GetGroupRequest]) (*connect_go.Response[v1.GetGroupResponse], error)
	GetGroups(context.Context, *connect_go.Request[v1.GetGroupsRequest]) (*connect_go.Response[v1.GetGroupsResponse], error)
	AddUser(context.Context, *connect_go.Request[v1.AddUserRequest]) (*connect_go.Response[v1.AddUserResponse], error)
	RemoveUser(context.Context, *connect_go.Request[v1.RemoveUserRequest]) (*connect_go.Response[v1.RemoveUserResponse], error)
}

// NewGroupServiceClient constructs a client for the authentication.v1.GroupService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGroupServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) GroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &groupServiceClient{
		createGroup: connect_go.NewClient[v1.CreateGroupRequest, v1.CreateGroupResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/CreateGroup",
			opts...,
		),
		updateGroup: connect_go.NewClient[v1.UpdateGroupRequest, v1.UpdateGroupResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/UpdateGroup",
			opts...,
		),
		deleteGroup: connect_go.NewClient[v1.DeleteGroupRequest, v1.DeleteGroupResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/DeleteGroup",
			opts...,
		),
		getGroup: connect_go.NewClient[v1.GetGroupRequest, v1.GetGroupResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/GetGroup",
			opts...,
		),
		getGroups: connect_go.NewClient[v1.GetGroupsRequest, v1.GetGroupsResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/GetGroups",
			opts...,
		),
		addUser: connect_go.NewClient[v1.AddUserRequest, v1.AddUserResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/AddUser",
			opts...,
		),
		removeUser: connect_go.NewClient[v1.RemoveUserRequest, v1.RemoveUserResponse](
			httpClient,
			baseURL+"/authentication.v1.GroupService/RemoveUser",
			opts...,
		),
	}
}

// groupServiceClient implements GroupServiceClient.
type groupServiceClient struct {
	createGroup *connect_go.Client[v1.CreateGroupRequest, v1.CreateGroupResponse]
	updateGroup *connect_go.Client[v1.UpdateGroupRequest, v1.UpdateGroupResponse]
	deleteGroup *connect_go.Client[v1.DeleteGroupRequest, v1.DeleteGroupResponse]
	getGroup    *connect_go.Client[v1.GetGroupRequest, v1.GetGroupResponse]
	getGroups   *connect_go.Client[v1.GetGroupsRequest, v1.GetGroupsResponse]
	addUser     *connect_go.Client[v1.AddUserRequest, v1.AddUserResponse]
	removeUser  *connect_go.Client[v1.RemoveUserRequest, v1.RemoveUserResponse]
}

// CreateGroup calls authentication.v1.GroupService.CreateGroup.
func (c *groupServiceClient) CreateGroup(ctx context.Context, req *connect_go.Request[v1.CreateGroupRequest]) (*connect_go.Response[v1.CreateGroupResponse], error) {
	return c.createGroup.CallUnary(ctx, req)
}

// UpdateGroup calls authentication.v1.GroupService.UpdateGroup.
func (c *groupServiceClient) UpdateGroup(ctx context.Context, req *connect_go.Request[v1.UpdateGroupRequest]) (*connect_go.Response[v1.UpdateGroupResponse], error) {
	return c.updateGroup.CallUnary(ctx, req)
}

// DeleteGroup calls authentication.v1.GroupService.DeleteGroup.
func (c *groupServiceClient) DeleteGroup(ctx context.Context, req *connect_go.Request[v1.DeleteGroupRequest]) (*connect_go.Response[v1.DeleteGroupResponse], error) {
	return c.deleteGroup.CallUnary(ctx, req)
}

// GetGroup calls authentication.v1.GroupService.GetGroup.
func (c *groupServiceClient) GetGroup(ctx context.Context, req *connect_go.Request[v1.GetGroupRequest]) (*connect_go.Response[v1.GetGroupResponse], error) {
	return c.getGroup.CallUnary(ctx, req)
}

// GetGroups calls authentication.v1.GroupService.GetGroups.
func (c *groupServiceClient) GetGroups(ctx context.Context, req *connect_go.Request[v1.GetGroupsRequest]) (*connect_go.Response[v1.GetGroupsResponse], error) {
	return c.getGroups.CallUnary(ctx, req)
}

// AddUser calls authentication.v1.GroupService.AddUser.
func (c *groupServiceClient) AddUser(ctx context.Context, req *connect_go.Request[v1.AddUserRequest]) (*connect_go.Response[v1.AddUserResponse], error) {
	return c.addUser.CallUnary(ctx, req)
}

// RemoveUser calls authentication.v1.GroupService.RemoveUser.
func (c *groupServiceClient) RemoveUser(ctx context.Context, req *connect_go.Request[v1.RemoveUserRequest]) (*connect_go.Response[v1.RemoveUserResponse], error) {
	return c.removeUser.CallUnary(ctx, req)
}

// GroupServiceHandler is an implementation of the authentication.v1.GroupService service.
type GroupServiceHandler interface {
	CreateGroup(context.Context, *connect_go.Request[v1.CreateGroupRequest]) (*connect_go.Response[v1.CreateGroupResponse], error)
	UpdateGroup(context.Context, *connect_go.Request[v1.UpdateGroupRequest]) (*connect_go.Response[v1.UpdateGroupResponse], error)
	DeleteGroup(context.Context, *connect_go.Request[v1.DeleteGroupRequest]) (*connect_go.Response[v1.DeleteGroupResponse], error)
	GetGroup(context.Context, *connect_go.Request[v1.GetGroupRequest]) (*connect_go.Response[v1.GetGroupResponse], error)
	GetGroups(context.Context, *connect_go.Request[v1.GetGroupsRequest]) (*connect_go.Response[v1.GetGroupsResponse], error)
	AddUser(context.Context, *connect_go.Request[v1.AddUserRequest]) (*connect_go.Response[v1.AddUserResponse], error)
	RemoveUser(context.Context, *connect_go.Request[v1.RemoveUserRequest]) (*connect_go.Response[v1.RemoveUserResponse], error)
}

// NewGroupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGroupServiceHandler(svc GroupServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/authentication.v1.GroupService/CreateGroup", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/CreateGroup",
		svc.CreateGroup,
		opts...,
	))
	mux.Handle("/authentication.v1.GroupService/UpdateGroup", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/UpdateGroup",
		svc.UpdateGroup,
		opts...,
	))
	mux.Handle("/authentication.v1.GroupService/DeleteGroup", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/DeleteGroup",
		svc.DeleteGroup,
		opts...,
	))
	mux.Handle("/authentication.v1.GroupService/GetGroup", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/GetGroup",
		svc.GetGroup,
		opts...,
	))
	mux.Handle("/authentication.v1.GroupService/GetGroups", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/GetGroups",
		svc.GetGroups,
		opts...,
	))
	mux.Handle("/authentication.v1.GroupService/AddUser", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/AddUser",
		svc.AddUser,
		opts...,
	))
	mux.Handle("/authentication.v1.GroupService/RemoveUser", connect_go.NewUnaryHandler(
		"/authentication.v1.GroupService/RemoveUser",
		svc.RemoveUser,
		opts...,
	))
	return "/authentication.v1.GroupService/", mux
}

// UnimplementedGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGroupServiceHandler struct{}

func (UnimplementedGroupServiceHandler) CreateGroup(context.Context, *connect_go.Request[v1.CreateGroupRequest]) (*connect_go.Response[v1.CreateGroupResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.CreateGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) UpdateGroup(context.Context, *connect_go.Request[v1.UpdateGroupRequest]) (*connect_go.Response[v1.UpdateGroupResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.UpdateGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) DeleteGroup(context.Context, *connect_go.Request[v1.DeleteGroupRequest]) (*connect_go.Response[v1.DeleteGroupResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.DeleteGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) GetGroup(context.Context, *connect_go.Request[v1.GetGroupRequest]) (*connect_go.Response[v1.GetGroupResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.GetGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) GetGroups(context.Context, *connect_go.Request[v1.GetGroupsRequest]) (*connect_go.Response[v1.GetGroupsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.GetGroups is not implemented"))
}

func (UnimplementedGroupServiceHandler) AddUser(context.Context, *connect_go.Request[v1.AddUserRequest]) (*connect_go.Response[v1.AddUserResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.AddUser is not implemented"))
}

func (UnimplementedGroupServiceHandler) RemoveUser(context.Context, *connect_go.Request[v1.RemoveUserRequest]) (*connect_go.Response[v1.RemoveUserResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("authentication.v1.GroupService.RemoveUser is not implemented"))
}
