grpc:
  address: http://localhost:8081
database:
  host: localhost
  port: 26257
  username: root
  database: authentication
  password: ""
  sslmode: disable
  timezone: UTC
  connect_timeout: 5
  maxRetries: 5
logger:
  development: false
  level: debug
metrics:
  jaegerAddress: "localhost:14268"
authServer:
  privateKey: ".build/keys/id_ed25519"