export enum SessionActionTypes { 
    DISPATCH_SIGN_IN_ACTION = 'DISPATCH_SIGN_IN_ACTION',
    SET_SIGN_IN_ACTION = 'SET_SIGN_IN_ACTION',

    DISPATCH_SIGN_OUT_ACTION = 'DISPATCH_SIGN_OUT_ACTION',
    SET_SIGN_OUT_ACTION = 'SET_SIGN_OUT_ACTION',

    DISPATCH_VALIDATE_SESSION_ACTION = 'DISPATCH_VALIDATE_SESSION',
    SET_VALIDATED_SESSION_ACTION = 'SET_VALIDATED_SESSION_ACTION',

    DISPATCH_VALIDATE_SESSION_PERMISSIONS_ACTION = 'DISPATCH_VALIDATE_SESSION_PERMISSIONS_ACTION',
    SET_VALIDATED_SESSION_PERMISSIONS_ACTION = 'SET_VALIDATED_SESSION_PERMISSIONS_ACTION'
}