export enum UserActionTypes {
  DISPATCH_SIGN_IN_ACTION = 'DISPATCH_SIGN_IN_ACTION',
  DISPATCH_SIGN_OUT_ACTION = 'DISPATCH_SIGN_OUT_ACTION',
  DISPATCH_SIGN_UP_ACTION = 'DISPATCH_SIGN_UP_ACTION',
  DISPATCH_RESET_PASSWORD_ACTION = 'DISPATCH_RESET_PASSWORD',
  DISPATCH_CREATE_SESSION_ACTION = 'DISPATCH_CREATE_SESSION',
  DISPATCH_VALIDATE_SESSION_ACTION = 'DISPATCH_VALIDATE_SESSION',
  SET_USER_INFORMATION_ACTION = 'SET_USER_INFORMATION_ACTION',
}
