// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package gardens

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Garden struct {
	ID            uuid.UUID
	Name          string
	Comment       string
	Location      string
	GrowType      string
	GrowSize      string
	GrowStyle     string
	ContainerSize string
	Tags          string
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}
