// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file authentication/v1/groups.proto (package authentication.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddGroupMemberRequest, AddGroupMemberResponse, CreateGroupRequest, CreateGroupResponse, DeleteGroupRequest, DeleteGroupResponse, GetGroupMembersRequest, GetGroupMembersResponse, GetGroupRequest, GetGroupResponse, GetGroupsRequest, GetGroupsResponse, GetUserGroupsRequest, GetUserGroupsResponse, RemoveGroupMemberRequest, RemoveGroupMemberResponse, UpdateGroupMemberRequest, UpdateGroupMemberResponse, UpdateGroupRequest, UpdateGroupResponse } from "./groups_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service authentication.v1.GroupService
 */
export const GroupService = {
  typeName: "authentication.v1.GroupService",
  methods: {
    /**
     * @generated from rpc authentication.v1.GroupService.CreateGroup
     */
    createGroup: {
      name: "CreateGroup",
      I: CreateGroupRequest,
      O: CreateGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.UpdateGroup
     */
    updateGroup: {
      name: "UpdateGroup",
      I: UpdateGroupRequest,
      O: UpdateGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.DeleteGroup
     */
    deleteGroup: {
      name: "DeleteGroup",
      I: DeleteGroupRequest,
      O: DeleteGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.GetGroup
     */
    getGroup: {
      name: "GetGroup",
      I: GetGroupRequest,
      O: GetGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.GetGroups
     */
    getGroups: {
      name: "GetGroups",
      I: GetGroupsRequest,
      O: GetGroupsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.AddGroupMember
     */
    addGroupMember: {
      name: "AddGroupMember",
      I: AddGroupMemberRequest,
      O: AddGroupMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.UpdateGroupMember
     */
    updateGroupMember: {
      name: "UpdateGroupMember",
      I: UpdateGroupMemberRequest,
      O: UpdateGroupMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.RemoveGroupMember
     */
    removeGroupMember: {
      name: "RemoveGroupMember",
      I: RemoveGroupMemberRequest,
      O: RemoveGroupMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.GetGroupMembers
     */
    getGroupMembers: {
      name: "GetGroupMembers",
      I: GetGroupMembersRequest,
      O: GetGroupMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.GroupService.GetUserGroups
     */
    getUserGroups: {
      name: "GetUserGroups",
      I: GetUserGroupsRequest,
      O: GetUserGroupsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

