// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package node

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Node struct {
	MacAddress   string
	Name         string
	OwnedBy      uuid.NullUUID
	CustomLabels pgtype.JSONB
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	AdoptedAt    sql.NullTime
}

type Sensor struct {
	ID       uuid.UUID
	Name     string
	NodeID   string
	Model    sql.NullString
	Category sql.NullInt32
}
