// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package node

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Node struct {
	MacAddress   string
	Name         string
	OwnedBy      pgtype.UUID
	CustomLabels []byte
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	AdoptedAt    pgtype.Timestamp
}

type Sensor struct {
	ID       pgtype.UUID
	Name     string
	NodeID   string
	Model    pgtype.Text
	Category pgtype.Int4
}
