// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file authentication/v1/user.proto (package authentication.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse, DeleteUserRequest, DeleteUserResponse, GetUsersRequest, GetUsersResponse, ResetUserPasswordRequest, ResetUserPasswordResponse, UpdateUserRequest, UpdateUserResponse } from "./user_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service authentication.v1.UserService
 */
export const UserService = {
  typeName: "authentication.v1.UserService",
  methods: {
    /**
     * @generated from rpc authentication.v1.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: DeleteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.UserService.ResetUserPassword
     */
    resetUserPassword: {
      name: "ResetUserPassword",
      I: ResetUserPasswordRequest,
      O: ResetUserPasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UpdateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authentication.v1.UserService.GetUsers
     */
    getUsers: {
      name: "GetUsers",
      I: GetUsersRequest,
      O: GetUsersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

