// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file garden/v1/garden.proto (package garden.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateGardenRequest, CreateGardenResponse, DeleteGardenRequest, DeleteGardenResponse, GetGardenRequest, GetGardenResponse, GetGardensRequest, GetGardensResponse, UpdateGardenRequest, UpdateGardenResponse } from "./garden_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service garden.v1.GardenService
 */
export const GardenService = {
  typeName: "garden.v1.GardenService",
  methods: {
    /**
     * @generated from rpc garden.v1.GardenService.CreateGarden
     */
    createGarden: {
      name: "CreateGarden",
      I: CreateGardenRequest,
      O: CreateGardenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.GardenService.DeleteGarden
     */
    deleteGarden: {
      name: "DeleteGarden",
      I: DeleteGardenRequest,
      O: DeleteGardenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.GardenService.UpdateGarden
     */
    updateGarden: {
      name: "UpdateGarden",
      I: UpdateGardenRequest,
      O: UpdateGardenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.GardenService.GetGardens
     */
    getGardens: {
      name: "GetGardens",
      I: GetGardensRequest,
      O: GetGardensResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.GardenService.GetGarden
     */
    getGarden: {
      name: "GetGarden",
      I: GetGardenRequest,
      O: GetGardenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

