// @generated by protoc-gen-connect-web v0.6.0 with parameter "target=ts"
// @generated from file garden/v1/recipe.proto (package garden.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateRecipeRequest, CreateRecipeResponse, DeleteRecipeRequest, DeleteRecipeResponse, GetRecipeRequest, GetRecipeResponse, GetRecipesRequest, GetRecipesResponse, UpdateRecipeRequest, UpdateRecipeResponse } from "./recipe_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service garden.v1.RecipeService
 */
export const RecipeService = {
  typeName: "garden.v1.RecipeService",
  methods: {
    /**
     * @generated from rpc garden.v1.RecipeService.CreateRecipe
     */
    createRecipe: {
      name: "CreateRecipe",
      I: CreateRecipeRequest,
      O: CreateRecipeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.RecipeService.DeleteRecipe
     */
    deleteRecipe: {
      name: "DeleteRecipe",
      I: DeleteRecipeRequest,
      O: DeleteRecipeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.RecipeService.UpdateRecipe
     */
    updateRecipe: {
      name: "UpdateRecipe",
      I: UpdateRecipeRequest,
      O: UpdateRecipeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.RecipeService.GetRecipes
     */
    getRecipes: {
      name: "GetRecipes",
      I: GetRecipesRequest,
      O: GetRecipesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc garden.v1.RecipeService.GetRecipe
     */
    getRecipe: {
      name: "GetRecipe",
      I: GetRecipeRequest,
      O: GetRecipeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

